<?php
/** @package Test::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("PedidoMap.php");

/**
 * PedidoDAO provides object-oriented access to the pedido table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Test::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class PedidoDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var date */
	public $Datacriacao;

	/** @var string */
	public $Observacao;

	/** @var date */
	public $Dataentrega;

	/** @var float */
	public $Valorfrete;

	/** @var float */
	public $Valordesconto;

	/** @var float */
	public $Valortotal;

	/** @var string */
	public $Statuspedido;

	/** @var string */
	public $Formapagamento;

	/** @var string */
	public $Vendedor;

	/** @var string */
	public $Cliente;

	/** @var string */
	public $Enderecoentrega;

	/** @var string */
	public $Itempedido;



}
?>